import { NavBar } from '@/components/nav-bar';
import { Footer } from '@/components/Footer';
import "@/style/globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="">
        <NavBar />
        {/* text before main */}
        <main className=""> 
          {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
